// AUTO-GENERATED by scripts/generate-diagnostic-kinds.mjs — do not edit.
// Run `pnpm gen:diagnostic-kinds` after changing AppError or SearchError.

export const DIAGNOSTIC_KINDS = [
  "action_failed",
  "auth_failure",
  "database_failure",
  "encryption_failure",
  "extension_crash",
  "extension_failure",
  "extension_proxy_error",
  "iframe_uncaught",
  "iframe_unhandled_rejection",
  "invoke_unknown",
  "io_failure",
  "json_failure",
  "lock_poisoned",
  "manual",
  "network_failure",
  "not_found",
  "oauth_failure",
  "panic",
  "permission_denied",
  "platform_failure",
  "power_failure",
  "render_error",
  "rpc_timeout",
  "search_io_failure",
  "search_json_failure",
  "search_lock_poisoned",
  "search_not_found",
  "search_other",
  "shortcut_failure",
  "uncaught_exception",
  "unhandled_rejection",
  "unknown",
  "validation_failure"
] as const;

export type DiagnosticKind = typeof DIAGNOSTIC_KINDS[number];
