// This file has been generated by Specta. Do not edit this file manually.
export type Application = {
	id?: string,
	name: string,
	path: string,
	usageCount?: number,
	icon?: string | null,
	lastUsedAt?: number | null,
};

export type Command = {
	id: string,
	name: string,
	extension: string,
	trigger: string,
	type: string,
	usageCount?: number,
	icon: string | null,
	lastUsedAt?: number | null,
};

export type SearchResult = {
	objectId: string,
	name: string,
	type: string,
	score: number,
	path?: string | null,
	icon?: string | null,
	extensionId?: string | null,
};

export type SearchableItem = { category: "application" } & Application | { category: "command" } & Command;
