// This file has been generated by Specta. Do not edit this file manually.
export type AliasConflict = {
	objectId: string,
	itemName: string,
};

export type AliasMatch = {
	objectId: string,
	itemType: string,
	autoExecute: boolean,
};

export type Application = {
	id?: string,
	name: string,
	path: string,
	usageCount?: number,
	icon?: string | null,
	lastUsedAt?: number | null,
	/**
	 *  Platform-native bundle / process identifier when discoverable:
	 *  - macOS: `CFBundleIdentifier` from `Contents/Info.plist` (e.g. `com.apple.Safari`)
	 *  - Linux: `StartupWMClass` from the `.desktop` entry, or the basename of `Exec=`
	 *    as a fallback (e.g. `firefox`)
	 *  - Windows: not extracted — `.lnk` shortcuts don't carry a bundle id
	 * 
	 *  Consumed by `IApplicationService.isRunning()` — extensions should prefer
	 *  this field over `name` when calling `isRunning`, with `name` as a fallback.
	 */
	bundleId?: string | null,
};

export type Command = {
	id: string,
	name: string,
	extension: string,
	trigger: string,
	type: string,
	usageCount?: number,
	icon: string | null,
	lastUsedAt?: number | null,
	subtitle?: string | null,
};

/**
 *  Represents a search result contributed by a frontend extension.
 *  Sent from TypeScript to Rust for unified ranking.
 */
export type ExternalSearchResult = {
	objectId: string,
	name: string,
	description?: string | null,
	type: string,
	score: number,
	icon?: string | null,
	extensionId?: string | null,
	category?: string | null,
	style?: string | null,
};

// A user-defined alias bound to a single search-index item (application or command).
export type ItemAlias = {
	objectId: string,
	alias: string,
	itemName: string,
	itemType: string,
	createdAt: number,
};

export type MergedSearchResponse = {
	results: SearchResult[],
	aliasMatch?: AliasMatch | null,
};

export type SearchResult = {
	objectId: string,
	name: string,
	type: string,
	score: number,
	path?: string | null,
	icon?: string | null,
	extensionId?: string | null,
	description?: string | null,
	style?: string | null,
	alias?: string | null,
};

export type SearchableItem = { category: "application" } & Application | { category: "command" } & Command;

// Input for updating a command's runtime metadata (currently: subtitle only).
export type UpdateCommandMetadataInput = {
	commandObjectId: string,
	subtitle: string | null,
};
