// This file has been generated by Specta. Do not edit this file manually.
export type Application = {
	id?: string,
	name: string,
	path: string,
	usageCount?: number,
	icon?: string | null,
	lastUsedAt?: number | null,
};

export type Command = {
	id: string,
	name: string,
	extension: string,
	trigger: string,
	type: string,
	usageCount?: number,
	icon: string | null,
	lastUsedAt?: number | null,
};

/**
 *  Represents a search result contributed by a frontend extension.
 *  Sent from TypeScript to Rust for unified ranking.
 */
export type ExternalSearchResult = {
	objectId: string,
	name: string,
	description?: string | null,
	type: string,
	score: number,
	icon?: string | null,
	extensionId?: string | null,
	category?: string | null,
	style?: string | null,
};

export type SearchResult = {
	objectId: string,
	name: string,
	type: string,
	score: number,
	path?: string | null,
	icon?: string | null,
	extensionId?: string | null,
	description?: string | null,
	style?: string | null,
};

export type SearchableItem = { category: "application" } & Application | { category: "command" } & Command;
